#!/bin/bash

clean(){
    rm -rf .shadow-cljs node_modules .cpcache resources/public/js-out
}

shadow(){
    ./node_modules/.bin/shadow-cljs "$@"
}

server(){
    shadow -A:core server
    # yarn server
}

test(){
    npm i
    shadow -A:core:dev:local watch test
}

dev(){
    npm i
    shadow -A:core:dev:local watch :app
    # npx shadow-cljs -A:dev:local watch app
    # yarn dev
}

release(){
    npm i
    shadow -A:core:optimized:local release app
}

dock() {

    docker build -t abc.app2 -f Dockerfile ../../
    docker run  --rm \
                --cpus=4.0 \
                --memory=4g \
                --name abc.app2 \
                -it \
                -p 5511:5511 \
                -p 5515:5515 \
                -p 5531:5531 \
                -v "$(cd ../../ && pwd)"/system:/ctx/system \
                -v "$(cd ../../ && pwd)"/apps/app2:/ctx/app \
                -e "appenv={:optimized false}" \
                 abc.app2 \
                 bash
}

"$@"